pipeline {
    agent any

    tools {
        maven "default"
    }

    stages {
        stage('Cloning') {
            steps {
                git branch: "main", url: 'https://github.com/pipecm/my-spring-boot-app.git'
            }
        }

        stage('Analysis') {
            steps {
                withSonarQubeEnv('sq-docker'){
                    sh "echo 'Starting SonarQube analysis'"
                    sh "mvn clean verify sonar:sonar -Dsonar.projectKey=my-spring-boot-app -Dsonar.projectName='my-spring-boot-app' -Dsonar.host.url=http://sonarqube-server:9000 -Dsonar.token=sqp_546501c47be566a813654533733329dcc78a82eb"
                    sh "echo 'Analysis finished successfully'"
                }
            }
        }

        stage('Build') {
            steps {
                sh "echo 'Starting build'"
                sh "mvn -Dmaven.test.failure.ignore=true clean package"
            }

            post {
                success {
                    sh "echo 'Build success'"
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }

        stage('Finish') {
            steps {
                sh "echo 'Deployment finished successfully'"
            }
        }
    }
}
